sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t howardt/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true howardt/docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-playground"
  env: "Docker-playground-env"
  bucket_name: "elasticbeanstalk-us-east-1-661256640887" # ElasticBeanstalk will store everything to this bucket from this region
  bucket_path: "docker-playground" # Before first deployment, nothing will be found in the bucket
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
